version: '3'

services:
  webdav:
    image: bytemark/webdav
    container_name: webdav
    restart: always
    ports:
      - "8070:80"
    environment:
      AUTH_TYPE: Digest
      USERNAME: booyah
      PASSWORD: repo
      ANONYMOUS_METHODS: ALL
    volumes:
      - /srv/dev-disk-by-uuid-8b938487-3837-4817-b082-33293ab9b6c6/global-sync/Sync/Samba/ServerShare/webdav:/var/lib/dav/data
